### ISSUE TITLE
2022 Q2 Roadmap

### ISSUE THREAD

**Issue by mengqcc** [arextest/arex-agent-java#5]
Version: 0.5
- [ ] Instrumentation: jedis2 
- [ ] Instrumentation: redission
- [ ] Instrumentation: lettuce
- [ ] Instrumentation: okhttp 2/3
- [ ] Instrumentation: dynamic type
- [ ] Instrumentation: gRPC (low priority)
- [ ] Instrumentation: Servlet5
- [ ] Instrumentation: Time machine (low priority)
- [ ] Framework: Ignore

**Comment by mengqcc** [comment]
- [ ] Instrumentation: jedis2 
- [ ] Framework: Ignore

**Comment by mr3** [comment]
- [ ] Instrumentation: Servlet5
- [ ] Instrumentation: lettuce

**Comment by mengqcc** [comment]
Because of the lower version, okhttp2 support is abandoned.
Grpc adjusted to Q3
